KerasH5: 'keras_model.h5'
InputData: ../../dataset/ad03_tb_input_features.dat
OutputPredictions: ../../dataset/ad03_tb_input_features.dat
OutputDir: anomaly_detector_prj
ProjectName: anomaly_detector
XilinxPart: xc7z020clg400-1
ClockPeriod: 10
Backend: Catapult
IOType: io_parallel
HLSConfig:
  Model:
    Precision: ap_fixed<32,16>
    ReuseFactor: 4096
    Strategy: Resource
  LayerName:
    batch_normalization:
      Precision:
        bias: ap_fixed<16,6>
        scale: ap_fixed<16,6>
      ReuseFactor: 4096
      Trace: true
      accum_t: ap_fixed<32,16>
    batch_normalization_1:
      Precision:
        bias: ap_fixed<16,6>
        scale: ap_fixed<16,6>
      ReuseFactor: 4096
      Trace: true
      accum_t: ap_fixed<32,16>
    batch_normalization_2:
      Precision:
        bias: ap_fixed<16,6>
        scale: ap_fixed<16,6>
      ReuseFactor: 4096
      Trace: true
      accum_t: ap_fixed<32,16>
    batch_normalization_3:
      Precision:
        bias: ap_fixed<16,6>
        scale: ap_fixed<16,6>
      ReuseFactor: 4096
      Trace: true
      accum_t: ap_fixed<32,16>
    batch_normalization_4:
      Precision:
        bias: ap_fixed<16,6>
        scale: ap_fixed<16,6>
      ReuseFactor: 4096
      Trace: true
      accum_t: ap_fixed<32,16>
    input_1:
      Precision: ap_fixed<8,8>
      ReuseFactor: 4096
      Trace: true
      accum_t: ap_fixed<32,16>
    q_activation:
      Precision:
        result: ap_fixed<7,4>
      ReuseFactor: 4096
      Trace: true
      accum_t: ap_fixed<32,16>
    q_activation_1:
      Precision:
        result: ap_fixed<5,3>
      ReuseFactor: 4096
      Trace: true
      accum_t: ap_fixed<32,16>
    q_activation_2:
      Precision:
        result: ap_fixed<6,4>
      ReuseFactor: 4096
      Trace: true
      accum_t: ap_fixed<32,16>
    q_activation_3:
      Precision:
        result: ap_fixed<6,4>
      ReuseFactor: 4096
      Trace: true
      accum_t: ap_fixed<32,16>
    q_activation_4:
      Precision:
        result: ap_fixed<5,3>
      ReuseFactor: 4096
      Trace: true
      accum_t: ap_fixed<32,16>
    q_dense:
      Precision:
        bias: ap_fixed<5,1>
        weight: ap_fixed<6,1>
      ReuseFactor: 4096
      Trace: true
      accum_t: ap_fixed<32,16>
    q_dense_1:
      Precision:
        bias: ap_fixed<9,4>
        weight: ap_fixed<6,1>
      ReuseFactor: 4096
      Trace: true
      accum_t: ap_fixed<32,16>
    q_dense_2:
      Precision:
        bias: ap_fixed<8,1>
        weight: ap_fixed<8,1>
      ReuseFactor: 4096
      Trace: true
      accum_t: ap_fixed<32,16>
    q_dense_3:
      Precision:
        bias: ap_fixed<7,1>
        weight: ap_fixed<3,2>
      ReuseFactor: 4096
      Trace: true
      accum_t: ap_fixed<32,16>
    q_dense_4:
      Precision:
        bias: ap_fixed<6,1>
        weight: ap_fixed<6,1>
      ReuseFactor: 4096
      Trace: true
      accum_t: ap_fixed<32,16>
    q_dense_5:
      Precision:
        bias: ap_fixed<9,4>
        weight: ap_fixed<5,1>
      ReuseFactor: 4096
      Trace: true
      accum_t: ap_fixed<32,16>
